name: Build

run-name: Build svelte kit

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18.x"
      - name: build
        run: |
          npm ci
          npm run build
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ github.token }}

